---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/jhu-library-devops/ansible-role-login-user
  name: login-user

- src: https://github.com/jhu-library-applications/ansible-role-deploy-keys
  name: deploy-keys

- src: https://github.com/geerlingguy/ansible-role-java
  name: java

- src: https://github.com/jhu-library-devops/ansible-role-ssl-certs.git
  name: ssl-certs

- src: https://github.com/geerlingguy/ansible-role-apache.git
  name: apache

- src: https://github.com/jhu-library-applications/ansible-role-passenger
  name: passenger

- src: https://github.com/jhu-library-applications/ansible-role-chruby
  name: chruby

- src: https://github.com/jhu-library-applications/ansible-role-mysql
  name: mysql

- src: https://github.com/jhu-library-applications/ansible-role-jetty
  name: jetty

- src: https://github.com/jhu-library-applications/ansible-role-shibboleth-sp
  name: shib

- src: https://github.com/jhu-library-devops/ansible-role-firewalld
  name: firewalld

- src: https://github.com/jhu-library-applications/ansible-role-bantheman
  name: bantheman

- src: https://github.com/arillso/ansible.logrotate.git
  name: logrotate

- src: https://github.com/jhu-library-applications/ansible-role-testup
  name: testup

- src: https://github.com/jhu-library-applications/ansible-role-solr
  name: solr

- src: https://github.com/jhu-library-applications/ansible-role-fail2ban
  name: fail2ban

- src: https://github.com/geerlingguy/ansible-role-nodejs
  name: ansible-role-nodejs
