---
- name: create login user for installation & configuration
  hosts: all

  roles:
  - { role: login-user, tags: ['login-user'] }

- name: secure SSH
  hosts: all
  become: true

  roles:
  - { role: secure-ssh, tags: ['secure-ssh'] }
